apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # 클러스터 핵심 인프라이므로 우선 배포
spec:
  project: default
  source:
    repoURL: https://emberstack.github.io/helm-charts
    chart: reflector
    targetRevision: 10.0.65
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system # 통상적으로 시스템 유틸리티는 kube-system 사용
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
