{{- range .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.metadata.name }}-{{ .name }}
  namespace: {{ $.Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Values.metadata.name }}
data:
  {{- range $key, $val := .data }}
  {{ $key }}: |
    {{- $val | nindent 4 }}
  {{- end }}
{{- end }}
