{{- if eq .Values.workload.kind "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.metadata.name }}
spec:
  replicas: {{ .Values.workload.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.metadata.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.metadata.name }}
    spec:
      containers:
      {{- range .Values.workload.containers }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          {{- if .ports }}
          ports:
          {{- range .ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
          {{- end }}
          {{- end }}
          {{- if .env }}
          env:
          {{- range .env }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- end }}
              {{- if .secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretKeyRef.name }}
                  key: {{ .secretKeyRef.key }}
              {{- end }}
          {{- end }}
          {{- end }}
      {{- end }}
{{- end }}
