{{- if eq .Values.workload.kind "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.metadata.name }}
spec:
  replicas: {{ .Values.workload.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.metadata.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.metadata.name }}
    spec:
      containers:
      {{- range .Values.workload.containers }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          {{- if .ports }}
          ports:
          {{- range .ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
          {{- end }}
          {{- end }}
          {{- if .env }}
          env:
          {{- range .env }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- end }}
              {{- if .secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretKeyRef.name }}
                  key: {{ .secretKeyRef.key }}
              {{- end }}
              {{- if .configMapKeyRef }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $.Values.metadata.name }}-{{ .configMapKeyRef.name }}
                  key: {{ .configMapKeyRef.key }}
              {{- end }}
          {{- end }}
          {{- end }}
          {{- if .envFrom }}
          envFrom:
          {{- range .envFrom }}
            {{- if .configMapRef }}
            - configMapRef:
                name: {{ $.Values.metadata.name }}-{{ .configMapRef.name }}
            {{- end }}
            {{- if .secretRef }}
            - secretRef:
                name: {{ .secretRef.name }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
          {{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
              {{- if hasKey . "readOnly" }}
              readOnly: {{ .readOnly }}
              {{- end }}
          {{- end }}
          {{- end }}
      {{- end }}
      {{- if .Values.workload.volumes }}
      volumes:
      {{- range .Values.workload.volumes }}
        - name: {{ .name }}
          {{- if .configMap }}
          configMap:
            name: {{ $.Values.metadata.name }}-{{ .configMap.name }}
          {{- end }}
          {{- if .secret }}
          secret:
            secretName: {{ .secret.secretName }}
          {{- end }}
      {{- end }}
      {{- end }}
{{- end }}
