apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab-workloads
  namespace: argocd
spec:
  description: Project for homelab AI workloads
  sourceRepos:
    - "https://github.com/robinjoon/Simple-K3S-Herness.git"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: "Namespace"
  namespaceResourceWhitelist:
    - group: "apps"
      kind: "Deployment"
    - group: "apps"
      kind: "ReplicaSet"
    - group: ""
      kind: "Pod"
    - group: ""
      kind: "Secret"
    - group: ""
      kind: "Service"
    - group: ""
      kind: "ConfigMap"
    - group: "networking.k8s.io"
      kind: "Ingress"
    - group: "cert-manager.io"
      kind: "Certificate"
    - group: "cert-manager.io"
      kind: "CertificateRequest"
    - group: "acme.cert-manager.io"
      kind: "Order"
    - group: "acme.cert-manager.io"
      kind: "Challenge"
    - group: "postgresql.cnpg.io"
      kind: "Database"
